--- # my conditional palybook
- hosts: all
  become: true
  user: ansible
  connection: ssh


  tasks:
    - name: install apche for debian
      command: apt-get install apache2 -y
      when: ansible_os_family == "Debian"


    - name: install apach for redhat
      command: yum install httpd -y
      when: ansible_os_family == "RedHat"
