--- # copying a file
- hosts: webservers
  user: ansible
  connection: ssh
  become: yes


  tasks:
    - name: copying a file
      copy:
        src: /home/ansible/index.html
        dest: /home/ansible
        owner: Bhoomi
