--- # creating multiple users
- hosts: all
  connection: ssh
  user: ansible
  become: true


  tasks:
    - name: creating multiple user accounts
      user: name='{{item}}' state=present
      with_items:
        - Geetha
        - Sahasra
        - Bhoomi
        - Deepu
        - Jagaeesh
