--- #deleting a file
- name: Deleting a file
  hosts: webservers
  connection: ssh
  become: true
  user: ansible


  tasks:
    - name: deleting a file
      file:
        path: /home/ansible/index.html
        state: absent
