--- # variables playbook
- hosts: webservers
  connection: ssh
  user: ansible
  become: yes


  vars_files:
    - users.yml


  tasks:
    - name: creating user {{user2}}
      user:
        name: '{{user2}}'
