--- # my vars section
- hosts: all
  connection: ssh
  become: true
  user: ansible


  vars:
    pkgname: httpd

  tasks:
    - name: installing httpd on webservers
      action: yum name='{{pkgname}}' state=present

